on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  commit:
    name: commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm install
      - run: npm run lint:js:fix
      - run: npm run lint:css:fix
      - run: npm run build
  merge:
    name: merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run lint:js:fix
      - run: npm run lint:css:fix
      - run: |
          npm run build
          npm run analyze
          npm run validate
      - run: npm run deploy
